power_consumption_list = {'single_board_computer': {'power': [2, 10], 'duty_cycle': 0.5},
                     'webcam': {'power': [0.6], 'duty_cycle': 1},
                     'gps': {'power': [0.04, 0.4], 'duty_cycle': 0.9},
                     'imu': {'power': [0.67, 1.1], 'duty_cycle': 0.9},
                     'sonar': {'power': [0.5, 50, 0.2], 'duty_cycle': 0.5},
                     'ph_sensor': {'power': [0.08, 0.1], 'duty_cycle': 0.95},
                     'temp_sensor': {'power': [0.04], 'duty_cycle': 1},
                     'wind_sensor': {'power': [0.67, 1.1], 'duty_cycle': 0.5},
                     'servo_motors': {'power': [0.4, 1.35], 'duty_cycle': 0.5},
                     'radio_transmitter': {'power': [0.5, 20], 'duty_cycle': 0.2}}